name: Build Linux Plugin
description: Compile the Linux plugin binary and upload the build artifact.
runs:
  using: composite
  steps:
    - uses: actions/checkout@v3

    - name: Get xplib
      shell: bash
      run: |
        git clone https://github.com/hotbso/xplib.git ../xplib

    - name: Build Linux binaries
      shell: bash
      run: |
        set -x
        sudo apt-get -y install libcurl4-openssl-dev libgl-dev libopengl-dev libopengl0 libx11-dev xorg-dev libglu1-mesa-dev
        TAG=${GITHUB_REF##*/}
        if [ ! -z "$TAG" ]; then
          echo "VERSION=$TAG" > version.mak
        fi
        make -f Makefile.lin64
        ls -lR ./build

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-linux
        path: |
          build/lin.xpl
          Ultralight-SDK-1.4.0-Linux/bin/*.so
          Ultralight-SDK-1.4.0-Linux/resources/*
